# Как должен хранить данные плагин
# Возможные варианты: MYSQL, SQLITE
storage-type: SQLITE

# Данный блок отвечает за настройки для удаленного хранилища (База данных).
# Вы должны настроить данные поля если используете следующие базы: MYSQL
data:
  host: localhost
  database: database
  username: username
  password: password
  port: 3306

# Это список серверов в которые плагин будет подключать не авторизованных игроков.
auth-servers:
  - AUTH-1:50 # Сервер с максимальным приоритетом, и с максимальным количеством на этом сервере который вы указали.
  - AUTH-2:100 # Плагин подключит игроков на данный сервер если подключение к предыдущему не удалась, либо она полная.

# Это список серверов в которые плагин будет подключать авторизованных игроков.
game-servers:
  - HUB-1:100 # Сервер с максимальным приоритетом, и с максимальным количеством на этом сервере который вы указали.
  - HUB-2:50 # Плагин подключит игроков на данный сервер если подключение к предыдущему не удалась, либо она полная.
  
# Определяет количество онлайн твинков игроков используя IP. Поставьте 0 чтобы отключить лимит
max-login-per-ip: 0

# Определяет максимальное количество привязок к одному и тому же vkId. Поставьте 0 чтобы отключить лимит
max-vk-link: 0

# Как плагин должен идентифицировать игроков
# Возможные варианты: UUID, NAME
id-type: NAME

# Если включено, плагин заблокирует попытку регистрации если у игрока неправильный регистр ника
# К примеру: Плагин заблокирует соединение игрока если он зарегестрировался как Notch и пытается зайти как: nOtCH, notch, NOTCH и т.д.
# Вы можете отключить эту опцию если используете id-type: UUID.
check-name-case: true

# RegEx паттерн разрешенных символом в нике игрока.
name-regex-pattern: '[a-zA-Z0-9_]*'

# RegEx паттерн для паролей игрока.
password-regex-pattern: '[a-zA-Z0-9_$#@^-]*'

# Как плагин должен хешировать пароли игроков
# Возможные варианты: MD5, SHA256, BCRYPT
hash-type: SHA256

# Должны ли писать подтверждать свои пароли при регистрации
enable-password-confirm: false
# Минимальная длина пароля
password-min-length: 5
# Максимальная длина пароля
password-max-length: 20
# Количество попыток ввода правильного пароля прежде чем игрока кикнет из сервера.
password-attempts: 3
# Как долго должна быть активна сессия по ip у игрока.
session-durability: 4h
# Сколько секунд у игроков есть прежде чем зарегестрироваться/залогиниться
auth-time: 60

# Доступные команды в ВК!
# /принять -> Подтверждение входа через ВК
# /отклонить -> Отклонение входа через ВК
# /отвязать [ник] -> для отвязки аккаунта
# /аккаунты -> Контроль аккаунтов через кнопки (Есть система страниц если больше 5 аккаунтов)
# /кик [ник] -> Кикнуть игрока с сервера
# /восстановить [ник] -> Кикает игрока с сервера если он онлайн, сбрасывает пароль на рандомный, и сбрасывает сессию
# /пароль [ник] [новый пароль] -> Меняет пароль аккаунта
# /код (/code) -> Для привязки майнкрафт аккаунта к ВК
# /админ-панель,/админпанель,/админ,/панель,/admin-panel,/adminpanel,/admin,/panel -> Можно контролировать привязанные, не привязанные аккаунты
# =============================================
# Доступные плейсхолдеры:
# %correct% - Правильный регистр ника
# %name%,%nick% = ник игрока
# %account_ip% = ip адрес игрока
# %vk_id% = vk id игрока, если у игрока нету привязанного vk, то покажет -1
# %country_code% = Покажет код страны (К примеру RU, UA, EN, KZ), работает только в сообщении подтверждения аккаунта
# %town% = Покажет город, работает только в сообщении подтверждения аккаунта
# %flag_emoji% = Покажет флаг страны в виде эмодзи, работает только в сообщении подтверждения аккаунта
vk:
  # Включена ли привязка к ВК, если вы отключите привязку игроки не смогут подтверждать вход, привязывать аккаунты.
  enabled: true
  # Юзеры ВК у которых будет админ доступ к привязанным аккаунтам
  # У юзеров с админ-доступом есть возможности:
  # 1. Отвязывать, менять ник, кикать используя обычные команды
  # 2. При вводе /adminpanel вам покажет админ панель
  admin-accounts:
    #205639000
    - 123456789 #Сюда ваш id вк
  confirmation: 
    # За сколько времени игрок должен привязать аккаунт (В секундах)
    remove-delay: 120
    code-length: 6
  enter:
    # За сколько секунд игрок должен подтвердить вход в аккаунт
    enter-delay: 60
  restore:
    code-length: 7
  # Создание комманд в вк, пригодится для создания таких команд как: /информация и так далее
  commands:
    # Команда при вводе которой бот пишет определенное сообщение
    /addvk:
      answer: 'ℹ Данную команду нужно писать на сервере!\nℹ Зайдите на сервер и напишите /addvk'
      chat: false # Отвечает за ответ в беседе, если поставить true -> Он будет отвечать в беседе, если поставить false -> Он не будет отвечать в беседе
      chat-answer: 'Данная команда отключена в беседе' #Если ответ в беседе отключён, то пишет такое сообщение при команде в беседе
    /test:
      answer: 'Бот работает!'
      chat: false # Если вы уберет chat-answer, бот будет игнорировать команду в беседах 
    command:
      #Если игрок ввел неизвестную команду то ему напишет то что команда не найдена
      regex: '^/(?!.*(принять|отклонить|отвязать|аккаунты|кик|восстановить|пароль|код|админ-панель|админпанель|админ|панель|admin-panel|adminpanel|admin|panel)).*$'
      answer: 'Команда не найдена! Доступные команды: /помощь'
      chat: false
  # Текст на кнопках в ВК
  button-labels:
    kick: 'Кикнуть'
    restore: 'Восстановить'
    return: 'Назад'
    next-page: '->'
    previous-page: '<-'
    account: '%name%'
    unlink: 'Отвязать'
    enter-confirm: 'Принять'
    enter-decline: 'Отклонить'
    admin-panel-all-accounts: 'Все аккаунты'
    admin-panel-all-linked-accounts: 'Все привязанные аккаунты'
  vkmessages: #Для переноса строк используйте "<br>" без кавычек.
    # Привязка ВК
    confirmation-error: 'Введен неправильный код! <br>Введите заного /addvk Ваш_Буквенный_Id и не постарайтесь не ошибится при вводе кода'
    confirmation-success: 'Вы успешно привязали аккаунт к ВК'
    confirmation-already-linked: 'Аккаунт уже привязан к другому ВК!'
    confirmation-no-code: '🤔 Произошла ошибка, возможно время кода истекло или вы ошиблись в вводе кода.<br>Чтобы привязать - напишите на сервере /addvk'
    confirmation-not-enough-arguments: 'Вы не указали код! Возможно вы забыли поставить пробел'
    # Общее
    not-your-account: 'Это не твой аккаунт!'
    # Список аккаунтов 
    no-accounts: 'У тебя нету аккаунтов'
    accounts: 'Твои аккаунты:'
    # Настройка аккаунта
    account-control: 'Настройка аккаунта: %name%'
    # Восстановление аккаунта
    restore-not-enough-arguments: 'Вы не указали ник игрока!'
    restored: 'Теперь пароль от аккаунта %name% - %password%'
    # Кик аккаунта
    kick-not-enough-arguments: 'Вы не указали ник игрока!'
    kick-starting: '✅ Аккаунт %nick% будет кикнут с сервера в течение 5 секунд если он находится на сервере!'
    player-offline: 'ℹ Игрок с ником %nick% не на сервере!'
    kicked: '%nick% был кикнут из сервера'
    # Смена пароля
    changepass-not-enough-arguments: 'Вы не указали ник и пароль игрока!'
    changepass-success: 'Успешно изменён пароль игрока %account% на %password%'
    # Подтверждение входа через ВК
    enter-no-enter: 'Вам не отправляли письмо для подтверждения входа 🤔' 
    enter-message: '⚠ Попытка авторизации на ваш аккаунт %nick% с IP адреса %account_ip%. Введите /принять или /отклонить, либо нажмите на кнопки'
    enter-kicked: 'Это был не ваш аккаунт, срочно смените пароль!'
    enter-confirmed: 'Вы успешно вошли в аккаунт!'
    # Отвязка аккаунта ВК
    unlink-not-enough-arguments: 'Вы не указали ник игрока!'
    unlinked: 'Вы успешно отвязали аккаунт %name%'
    # Админ-панель
    admin-panel: 'Админ панель:'
    
messages:
  # Регистрация
  register-chat: '&fПожалуйста зарегистрируйтесь командой &e/register <пароль>'
  register-title: '&eРегистрация'
  register-subtitle: '&fПожалуйста введите &e/register <пароль>'
  # Логин
  login-chat: '&fПожалуйста войдите используя команду &e/login <password>'
  login-title: '&eАвторизация'
  login-subtitle: '&fПожалуйста введите &e/login <пароль>'
  # Подтверждение входа через ВК
  vk-enter-confirm-need-chat: '&fПодтвердите вход в &9ВК &fдля того чтобы войти в игру'
  vk-enter-confirm-need-title: '&fПодтверждение &9ВК'
  vk-enter-confirm-need-subtitle: '&fПожалуйста подтвердите в &9ВК'
  # Ошибки
  time-left: '&cВремя вышло! Пожалуйста, попробуйте снова.'
  limit-ip-reached: '&cВы находитесь онлайн с большим количеством аккаунтов!'
  illegal-name-chars: '&cВ вашем никнейме содержатся недопустимые символы!'
  attempts-limit: '&cВы достигли лимита ввода паролей!'
  auth-servers-connection-refused: '&cОшибка при подключении к серверу авторизации. Пожалуйста попробуйте позже'
  game-servers-connection-refused: '&cОшибка при подключении к серверу лобби. Пожалуйста попробуйте позже'
  disabled-command: '&cЭта команда отключена до тех пор пока вы не авторизуетесь!'
  players-only: '&cКоманда только для игроков!'
  already-logged-in: '&cВы уже авторизованы.'
  already-logged-out: '&cВы не авторизованы.'
  account-exists: '&cТакой аккаунт уже существует. Пожалуйста, войдите.'
  account-not-found: '&cАккаунт не найден! Пожалуйста, зарегистрируйтесь.'
  # Авторизация
  player-offline: 'Игрок оффлайн!'
  force-connect-success: 'Игрок успешно подключен на сервер!'
  enter-password: '&cПожалуйста введите ваш пароль.'
  enter-new-password: '&cПожалуйста введите ваш старый пароль и новый пароль.'
  wrong-old-password: '&cНеверный пароль!'
  nothing-to-change: '&cВаши пароли совпдают.'
  change-success: '&aВаш пароль был изменён.'
  confirm-password: '&cПожалуйста подтвердите ваш пароль.'
  confirm-failed: '&cПароли разные!'
  password-too-short: '&cВаш пароль слишком короткий!'
  password-too-long: '&cВаш пароль слишком длинный!'
  illegal-password-chars: '&cВаш пароль содержит недопустимые символы!'
  wrong-password: '&cНеверный пароль. У вас осталось ещё %attempts% попыток.'
  register-success: '&aРегистрация прошла успешно.'
  login-success: '&aВы успешно авторизовались.'
  logout-success: '&aВы вышли из аккаунта'
  # ВК
  vk-disabled: '&cПривязка к ВК отключена'
  vk-usage: '&a/addvk буквенный_id'
  vk-link-limit-reached: 'Слишком много привязанных аккаунтов на данный ВК'
  already-linked: '&cВы уже привязали аккаунт ВК'
  screen-name-not-exists: '&cТакого буквенного id не существует'
  vk-send-code-error: '&cПроизошла ошибка при отправке сообщения на данный id, свяжитесь с администрацией'
  confirmation-vk-sent: '&aВсё почти готов. Напиши в личные сообщения в группу &lhttps://vk.com/examplegroup: /CODE %code% После ввода бот Вконтакте ответит вам что всё прошло успешно'
  vk-already-sent: '&cВы уже отправили код в ВК. Пожалуйста проверьте ваши сообщения ВК'
  vk-linked: '&cУспешно привязан аккаунт'
  vk-kicked: '&cВы были кикнуты из сервера по запросу ВК'
  vk-enter-confirmed: '&aВы подтвердили аккаунт в вк'
  vk-enter-declined: '&cВы отклонили вход с аккаунта ВК'
  # Подключение
  autoconnect: '&aСессия восстановлена. Присоеденяем Вас к серверу...'
  check-name-case-failed: '&cНеправильное имя. Аккаунт зарегистрирован под ником %correct%.'
  no-permission: '&cУ вас недостаточно прав для этого.'
  info-registered: '&fИгроков зарегистрировано: &e%players%'
  info-auth: '&fИгроков на сервере авторизации: &e%players%'
  info-version: '&fВерсия: &e%version%'
